# ----- Template UI ------
BUILD_LANGUAGES="en-US,it-IT,fr-FR"
BUILD_CMS="sanity"
NEXT_PUBLIC_SITE_NAME=
NEXT_PUBLIC_SITE_URL="http://localhost:3000"

# ----- Commerce Layer ------
CL_CLIENT_ID="rybI1HykhQ0RfsdwFhgR8D8TPsnbUoj2TaImr3fA_dQ"
CL_ENDPOINT="https://metal-ch.commercelayer.io"

# ----- Sanity Studio ------
NEXT_PUBLIC_SANITY_PROJECT_TITLE="CommerceLayerMetalCh"
NEXT_PUBLIC_SANITY_PROJECT_ID="6087dfkg"
NEXT_PUBLIC_SANITY_DATASET="production"
NEXT_PUBLIC_SANITY_API_VERSION="2022-10-25"
NEXT_PUBLIC_SANITY_TOKEN="skfHBkeDkJE8zu7aUk9dEIddjhMyBGR2bNFpYfNNqwDKTkpXVpqsNDVk1vhRTHZn1ABV95HdRocy5jnXOJsaZvfLypaZmEecTgqDNKAHVVb4ddNDCLijl4wwwa3ZLSAD1hvEoaFUtVz1U9tNw2UKj7rORHbUw57bsw1XhJkgAl8DxR1sPsuz"